import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {
  ChakraProvider,
  Flex,
  cookieStorageManagerSSR,
  localStorageManager,
} from "@chakra-ui/react";
import ThemeProvider from "./theme-provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  cookies,
  children,
}: Readonly<{
  cookies: string | Record<string, string>;
  children: React.ReactNode;
}>) {
  const colorModeManager =
    typeof cookies === "string"
      ? cookieStorageManagerSSR(cookies)
      : localStorageManager;

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ChakraProvider colorModeManager={colorModeManager}>
          <ThemeProvider>
            <Flex direction="column" minH="100vh">
              <Flex flex="1" direction="column" minH="90vh">
                <Header />
                {children}
              </Flex>
              <Footer />
            </Flex>
          </ThemeProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
