import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { store } from "../store";
import { Provider } from "react-redux";
import {
  ChakraProvider,
  cookieStorageManagerSSR,
  localStorageManager,
} from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  cookies,
  children,
}: Readonly<{
  cookies: string | Record<string, string>;
  children: React.ReactNode;
}>) {
  const colorModeManager =
    typeof cookies === "string"
      ? cookieStorageManagerSSR(cookies)
      : localStorageManager;

  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider colorModeManager={colorModeManager}>
          <Provider store={store}>{children}</Provider>
        </ChakraProvider>
      </body>
    </html>
  );
}
